/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Murrayy
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logSessionButton = new javax.swing.JButton();
        editLocationButton = new javax.swing.JButton();
        editSpeciesButton = new javax.swing.JButton();
        viewStatsButton = new javax.swing.JButton();
        editBaitButton = new javax.swing.JButton();
        latchedOntoLeviathansLabel = new javax.swing.JLabel();
        programmerLabel = new javax.swing.JLabel();
        waterImageLabel = new javax.swing.JLabel();
        waterImageLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logSessionButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        logSessionButton.setText("Log Session");
        logSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logSessionButtonActionPerformed(evt);
            }
        });

        editLocationButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        editLocationButton.setText("Edit location");
        editLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLocationButtonActionPerformed(evt);
            }
        });

        editSpeciesButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        editSpeciesButton.setText("Edit Species");
        editSpeciesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSpeciesButtonActionPerformed(evt);
            }
        });

        viewStatsButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        viewStatsButton.setText("View Stats");
        viewStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatsButtonActionPerformed(evt);
            }
        });

        editBaitButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        editBaitButton.setText("Edit Bait/Trace/Lure");
        editBaitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBaitButtonActionPerformed(evt);
            }
        });

        latchedOntoLeviathansLabel.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        latchedOntoLeviathansLabel.setText("LATCHED ONTO LEVIATHANS");

        programmerLabel.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        programmerLabel.setText("by Murray Yoko");

        waterImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sea-water.png"))); // NOI18N

        waterImageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sea-water.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editBaitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(editSpeciesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(logSessionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(viewStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(waterImageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waterImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programmerLabel)
                            .addComponent(latchedOntoLeviathansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(latchedOntoLeviathansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programmerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSpeciesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editBaitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSpeciesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSpeciesButtonActionPerformed
        // TODO add your handling code here:
        dispose();

		//create a new main menu screen.
		new EditSpeciesScreen().setVisible(true);
    }//GEN-LAST:event_editSpeciesButtonActionPerformed

    private void editLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLocationButtonActionPerformed
        // TODO add your handling code here:
        dispose();

		//create a new main menu screen.
		new EditLocationScreen().setVisible(true);
    }//GEN-LAST:event_editLocationButtonActionPerformed

    private void viewStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatsButtonActionPerformed
        // TODO add your handling code here:
        dispose();

		//create a new main menu screen.
		new ViewStatsScreen().setVisible(true);
    }//GEN-LAST:event_viewStatsButtonActionPerformed

    private void logSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logSessionButtonActionPerformed
        // TODO add your handling code here:
        dispose();

		//create a new main menu screen.
		new LogSessionScreen().setVisible(true);
    }//GEN-LAST:event_logSessionButtonActionPerformed

    private void editBaitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBaitButtonActionPerformed
        // TODO add your handling code here:
        dispose();

		//create a new main menu screen.
		new EditBaitScreen().setVisible(true);
    }//GEN-LAST:event_editBaitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBaitButton;
    private javax.swing.JButton editLocationButton;
    private javax.swing.JButton editSpeciesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel latchedOntoLeviathansLabel;
    private javax.swing.JButton logSessionButton;
    private javax.swing.JLabel programmerLabel;
    private javax.swing.JButton viewStatsButton;
    private javax.swing.JLabel waterImageLabel;
    private javax.swing.JLabel waterImageLabel2;
    // End of variables declaration//GEN-END:variables
}
